//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materia
    {
        public byte IdMateria { get; set; }
        public string Nombre { get; set; }
        public Nullable<byte> Creditos { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<byte> IdSemestre { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public byte[] Imagen { get; set; }
    
        public virtual Semestre Semestre { get; set; }
    }
}
